AIM.Admin.Web/AIM/AIM.Web.Admin/Models/EntityModels/PersonalInfo.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using TrackableEntities;
using TrackableEntities.Client;
using System.ComponentModel.DataAnnotations;

namespace AIM.Web.Admin.Models.EntityModels
{
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class PersonalInfo : ModelBase<PersonalInfo>, IEquatable<PersonalInfo>, ITrackable
    {
        public PersonalInfo()
        {
            this.Users = new ChangeTrackingCollection<User>();
        }

        [DataMember]
        [Display(Name = "Personal Info ID")]
        public int PersonalInfoId
        {
            get { return _PersonalInfoId; }
            set
            {
                if (Equals(value, _PersonalInfoId)) return;
                _PersonalInfoId = value;
                NotifyPropertyChanged(m => m.PersonalInfoId);
            }
        }

        private int _PersonalInfoId;

        [DataMember]
        [Display(Name = "Alias")]
        public string Alias
        {
            get { return _Alias; }
            set
            {
                if (Equals(value, _Alias)) return;
                _Alias = value;
                NotifyPropertyChanged(m => m.Alias);
            }
        }

        private string _Alias;

        [DataMember]
        [Display(Name = "Street")]
        public string Street
        {
            get { return _Street; }
            set
            {
                if (Equals(value, _Street)) return;
                _Street = value;
                NotifyPropertyChanged(m => m.Street);
            }
        }

        private string _Street;

        [DataMember]
        [Display(Name = "Street 2")]
        public string Street2
        {
            get { return _Street2; }
            set
            {
                if (Equals(value, _Street2)) return;
                _Street2 = value;
                NotifyPropertyChanged(m => m.Street2);
            }
        }

        private string _Street2;

        [DataMember]
        [Display(Name = "City")]
        public string City
        {
            get { return _City; }
            set
            {
                if (Equals(value, _City)) return;
                _City = value;
                NotifyPropertyChanged(m => m.City);
            }
        }

        private string _City;

        [DataMember]
        [Display(Name = "State")]
        public StateEnum? State
        {
            get { return _state; }
            set
            {
                if (Equals(value, _state)) return;
                _state = value;
                NotifyPropertyChanged(m => m.State);
            }
        }

        private StateEnum? _state;

        [DataMember]
        [Display(Name = "Zip Code")]
        public string Zip
        {
            get { return _Zip; }
            set
            {
                if (Equals(value, _Zip)) return;
                _Zip = value;
                NotifyPropertyChanged(m => m.Zip);
            }
        }

        private string _Zip;

        [DataMember]
        [Display(Name = "Phone Number")]
        public string Phone
        {
            get { return _Phone; }
            set
            {
                if (Equals(value, _Phone)) return;
                _Phone = value;
                NotifyPropertyChanged(m => m.Phone);
            }
        }

        private string _Phone;

        [DataMember]
        [Display(Name = "User ID")]
        public int? UserId
        {
            get { return _UserId; }
            set
            {
                if (Equals(value, _UserId)) return;
                _UserId = value;
                NotifyPropertyChanged(m => m.UserId);
            }
        }

        private int? _UserId;

        [DataMember]
        [Display(Name = "Users")]
        public ChangeTrackingCollection<User> Users
        {
            get { return _Users; }
            set
            {
                if (Equals(value, _Users)) return;
                _Users = value;
                NotifyPropertyChanged(m => m.Users);
            }
        }

        private ChangeTrackingCollection<User> _Users;

        #region Change Tracking

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }

#pragma warning disable 414

        [JsonProperty, DataMember]
        private Guid _entityIdentity = default(Guid);

#pragma warning restore 414

        bool IEquatable<PersonalInfo>.Equals(PersonalInfo other)
        {
            if (EntityIdentifier != default(Guid))
                return EntityIdentifier == other.EntityIdentifier;
            return false;
        }

        #endregion Change Tracking
    }
}

AIM.Admin.Web/AIM/AIM.Web.Admin/Controllers/PersonalInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AIM.Web.Admin.Client;
using AIM.Web.Admin.Models.EntityModels;

namespace AIM.Web.Admin.Controllers
{
    public class PersonalInfoController : Controller
    {
        private readonly PersonalInfoServiceClient _client = new PersonalInfoServiceClient();

        // GET: /PersonalInfo/
        public async Task<ActionResult> Index()
        {
            var personalInfo = await _client.GetPersonalInfos();

            return View(personalInfo);
        }

        // GET: /PersonalInfo/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PersonalInfo personalinfo = await _client.GetPersonalInfoById(id);
            if (personalinfo == null)
            {
                return HttpNotFound();
            }

            return View(personalinfo);
        }

        // GET: /PersonalInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /PersonalInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "PersonalInfoId,alias,street,street2,city,state,zip,phone,userId")] PersonalInfo personalinfo)
        {
            setDefaultValues(ref personalinfo);

            if (ModelState.IsValid)
            {
                await _client.CreatePersonalInfo(personalinfo);
                return RedirectToAction("Index");
            }

            return View(personalinfo);
        }

        private void setDefaultValues(ref PersonalInfo personalinfo)
        {
            // Dash was used because space gets treated as
            // an empty field by the either the view or the controller
            // which messes up the details display

            if (personalinfo.Alias == null)
                personalinfo.Alias = "-";

            if (personalinfo.Street == null)
                personalinfo.Street = "-";

            if (personalinfo.Street2 == null)
                personalinfo.Street2 = "-";

            if (personalinfo.City == null)
                personalinfo.City = "-";

            // State is required when creating PersonalInfo

            if (personalinfo.Zip == null)
                personalinfo.Zip = "-";

            if (personalinfo.Phone == null)
                personalinfo.Phone = "-";

            if (personalinfo.UserId == null)
                personalinfo.UserId = -1;
        }

        // GET: /PersonalInfo/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalInfo personalinfo = await _client.GetPersonalInfoById(id);

            if (personalinfo == null)
            {
                return HttpNotFound();
            }
            return View(personalinfo);
        }

        // POST: /PersonalInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "PersonalInfoId,alias,street,street2,city,state,zip,phone,userId")] PersonalInfo personalinfo)
        {
            if (ModelState.IsValid)
            {
                await _client.DeletePersonalInfo(personalinfo.PersonalInfoId);
                await _client.CreatePersonalInfo(personalinfo);

                return RedirectToAction("Index");
            }
            return View(personalinfo);
        }

        // GET: /PersonalInfo/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PersonalInfo personalinfo = await _client.GetPersonalInfoById(id);

            if (personalinfo == null)
            {
                return HttpNotFound();
            }
            return View(personalinfo);
        }

        // POST: /PersonalInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _client.DeletePersonalInfo(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            var dispose = _client as IDisposable;
            if (dispose != null)
            {
                dispose.Dispose();
            }
        }
    }
}

AIM.Admin.Web/AIM/AIM.Web.Admin/Views/PersonalInfo/Create.cshtml
@model AIM.Web.Admin.Models.EntityModels.PersonalInfo

@{
    ViewBag.Title = "Create";
    var ActiveUserName = TempData["ActiveUserName"];
    TempData["ActiveUserName"] = ActiveUserName;
    var ActivePermissions = TempData["ActivePermissions"];
    TempData["ActivePermissions"] = ActivePermissions;
}

@if (ActiveUserName != null)
{
    if (ActivePermissions.ToString() != "Employee")
    {

<h2>Create</h2>

using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PersonalInfo</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Alias, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alias)
                @Html.ValidationMessageFor(model => model.Alias)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street)
                @Html.ValidationMessageFor(model => model.Street)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street2)
                @Html.ValidationMessageFor(model => model.Street2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State)
                @Html.ValidationMessageFor(model => model.State)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip)
                @Html.ValidationMessageFor(model => model.Zip)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone)
                @Html.ValidationMessageFor(model => model.Phone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}

AIM.Admin.Web/AIM/AIM.Web.Admin/Views/PersonalInfo/Delete.cshtml
@model AIM.Web.Admin.Models.EntityModels.PersonalInfo

@{
    ViewBag.Title = "Delete";
    var ActiveUserName = TempData["ActiveUserName"];
    TempData["ActiveUserName"] = ActiveUserName;
    var ActivePermissions = TempData["ActivePermissions"];
    TempData["ActivePermissions"] = ActivePermissions;
}

@if (ActiveUserName != null)
{
    if (ActivePermissions.ToString() != "Employee")
    {

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonalInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}

AIM.Admin.Web/AIM/AIM.Web.Admin/Views/PersonalInfo/Index.cshtml
@model IEnumerable<AIM.Web.Admin.Models.EntityModels.PersonalInfo>

@{
    ViewBag.Title = "Index";
    var ActiveUserName = TempData["ActiveUserName"];
    TempData["ActiveUserName"] = ActiveUserName;
    var ActivePermissions = TempData["ActivePermissions"];
    TempData["ActivePermissions"] = ActivePermissions;
}

@if (ActiveUserName != null)
{ 
    if (ActivePermissions.ToString() != "Employee")
    {

<div>
    <ul class="breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Home")">Home</a><span class="divider">/</span>
        </li>
        <li>
            <a href="@Url.Action("Index", "PersonalInfo")">Personal Information</a>
        </li>
    </ul>
</div>


<div>
    <a class="btn btn-success" href="@Url.Action("Create", "PersonalInfo")">
        <i class="icon-plus icon-white"></i><i class="icon-user icon-white"></i>
        Create New
    </a>
</div>


<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i> PERSONAL INFORMATION</h2>
            <div class="box-icon">
                @*<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>*@
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>

        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Alias)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Street)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Street2)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.City)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.State)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Zip)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Phone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UserId)
                        </th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Alias)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Street)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Street2)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.City)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.State)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Zip)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Phone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserId)
                            </td>
                            <td class="center">
                                <div>
                                    <a class="btn btn-success" href="@Url.Action("Edit", "PersonalInfo", new { id = item.PersonalInfoId })">
                                        <i class="icon-zoom-in icon-white"></i>
                                        Edit
                                    </a>
                                </div>
                            </td>
                            <td class="center">
                                <div>
                                    <a class="btn btn-info" href="@Url.Action("Details", "PersonalInfo", new { id = item.PersonalInfoId })">
                                        <i class="icon-edit icon-white"></i>
                                        Details
                                    </a>
                                </div>
                            </td>
                            <td class="center">
                                <div>
                                    <a class="btn btn-danger" href="@Url.Action("Delete", "PersonalInfo", new { id = item.PersonalInfoId })">
                                        <i class="icon-trash icon-white"></i>
                                        Delete
                                    </a>

                                </div>
                            </td>
                        </tr>
                    }

            </table>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}
}
else
{
<div class="container-fluid">

    <div class="row-fluid">
        <div class="row-fluid">
            <div class="span12 center login-header" style="margin-bottom: 150px">
                <h2>Welcome to AIM Admin</h2>
                <div class="img-thumbnail">
                    <img src="~/img/AIMTitlePageLogo.png" height="170" width="240" />
                </div>
            </div><!--/span-->
        </div><!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    You are not authorized to view this page.
                </div>

                <section id="loginForm">
                    <div>
                        <a class="btn btn-success" href="@Url.Action("Index", "Home")">
                            <i class="icon-zoom-in icon-white"></i>
                            Home
                        </a>
                    </div>

                </section>

            </div><!--/span-->
        </div><!--/row-->
    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
}