AIM.Web.ClientApp/AIM.Web.ClientApp/Models/EntityModels/OpenJob.cs
using System.Collections;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using TrackableEntities;
using TrackableEntities.Client;

namespace AIM.Web.ClientApp.Models.EntityModels
{
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class OpenJob : ModelBase<OpenJob>, IEquatable<OpenJob>, ITrackable, IEnumerable
    {
        [DataMember]
        public int OpenJobsId
        {
            get { return _OpenJobsId; }
            set
            {
                if (Equals(value, _OpenJobsId)) return;
                _OpenJobsId = value;
                NotifyPropertyChanged(m => m.OpenJobsId);
            }
        }

        private int _OpenJobsId;

        [DataMember]
        public int JobId
        {
            get { return _JobId; }
            set
            {
                if (Equals(value, _JobId)) return;
                _JobId = value;
                NotifyPropertyChanged(m => m.JobId);
            }
        }

        private int _JobId;

        [DataMember]
        public int StoreId
        {
            get { return _StoreId; }
            set
            {
                if (Equals(value, _StoreId)) return;
                _StoreId = value;
                NotifyPropertyChanged(m => m.StoreId);
            }
        }

        private int _StoreId;

        [DataMember]
        public int RegionId
        {
            get { return _RegionId; }
            set
            {
                if (Equals(value, _RegionId)) return;
                _RegionId = value;
                NotifyPropertyChanged(m => m.RegionId);
            }
        }

        private int _RegionId;

        [DataMember]
        public Nullable<bool> IsApproved
        {
            get { return _IsApproved; }
            set
            {
                if (Equals(value, _IsApproved)) return;
                _IsApproved = value;
                NotifyPropertyChanged(m => m.IsApproved);
            }
        }

        private Nullable<bool> _IsApproved;

        [DataMember]
        public Job Job
        {
            get { return _Job; }
            set
            {
                if (Equals(value, _Job)) return;
                _Job = value;
                JobChangeTracker = _Job == null ? null
                    : new ChangeTrackingCollection<Job> { _Job };
                NotifyPropertyChanged(m => m.Job);
            }
        }

        private Job _Job;

        private ChangeTrackingCollection<Job> JobChangeTracker { get; set; }

        [DataMember]
        public Store Store
        {
            get { return _Store; }
            set
            {
                if (Equals(value, _Store)) return;
                _Store = value;
                StoreChangeTracker = _Store == null ? null
                    : new ChangeTrackingCollection<Store> { _Store };
                NotifyPropertyChanged(m => m.Store);
            }
        }

        private Store _Store;

        private ChangeTrackingCollection<Store> StoreChangeTracker { get; set; }

        [DataMember]
        public Region Region
        {
            get { return _Region; }
            set
            {
                if (Equals(value, _Region)) return;
                _Region = value;
                RegionChangeTracker = _Region == null ? null
                    : new ChangeTrackingCollection<Region> { _Region };
                NotifyPropertyChanged(m => m.Region);
            }
        }

        private Region _Region;

        private ChangeTrackingCollection<Region> RegionChangeTracker { get; set; }

        #region Change Tracking

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }

#pragma warning disable 414

        [JsonProperty, DataMember]
        private Guid _entityIdentity = default(Guid);

#pragma warning restore 414

        bool IEquatable<OpenJob>.Equals(OpenJob other)
        {
            if (EntityIdentifier != default(Guid))
                return EntityIdentifier == other.EntityIdentifier;
            return false;
        }

        #endregion Change Tracking

        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}

AIM.Web.ClientApp/AIM.Web.ClientApp/Models/EntityModels/Questionnaire.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using TrackableEntities;
using TrackableEntities.Client;

namespace AIM.Web.ClientApp.Models.EntityModels
{
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class Questionnaire : ModelBase<Questionnaire>, IEquatable<Questionnaire>, ITrackable
    {
        public Questionnaire()
        {
            this.Jobs = new ChangeTrackingCollection<Job>();
            this.Questions = new ChangeTrackingCollection<Question>();
        }

        [DataMember]
        public int QuestionnaireId
        {
            get { return _QuestionnaireId; }
            set
            {
                if (Equals(value, _QuestionnaireId)) return;
                _QuestionnaireId = value;
                NotifyPropertyChanged(m => m.QuestionnaireId);
            }
        }

        private int _QuestionnaireId;

        [DataMember]
        public int? QuestionId
        {
            get { return _QuestionId; }
            set
            {
                if (Equals(value, _QuestionId)) return;
                _QuestionId = value;
                NotifyPropertyChanged(m => m.QuestionId);
            }
        }

        private int? _QuestionId;

        [DataMember]
        public int? JobId
        {
            get { return _JobId; }
            set
            {
                if (Equals(value, _JobId)) return;
                _JobId = value;
                NotifyPropertyChanged(m => m.JobId);
            }
        }

        private int? _JobId;

        [DataMember]
        public ChangeTrackingCollection<Job> Jobs
        {
            get { return _Jobs; }
            set
            {
                if (Equals(value, _Jobs)) return;
                _Jobs = value;
                NotifyPropertyChanged(m => m.Jobs);
            }
        }

        private ChangeTrackingCollection<Job> _Jobs;

        [DataMember]
        public ChangeTrackingCollection<Question> Questions
        {
            get { return _Questions; }
            set
            {
                if (value != null) value.Parent = this;
                if (Equals(value, _Questions)) return;
                _Questions = value;
                NotifyPropertyChanged(m => m.Questions);
            }
        }

        private ChangeTrackingCollection<Question> _Questions;

        #region Change Tracking

        [DataMember]
        public TrackingState TrackingState { get; set; }

        [DataMember]
        public ICollection<string> ModifiedProperties { get; set; }

        [JsonProperty, DataMember]
        private Guid EntityIdentifier { get; set; }

#pragma warning disable 414

        [JsonProperty, DataMember]
        private Guid _entityIdentity = default(Guid);

#pragma warning restore 414

        bool IEquatable<Questionnaire>.Equals(Questionnaire other)
        {
            if (EntityIdentifier != default(Guid))
                return EntityIdentifier == other.EntityIdentifier;
            return false;
        }

        #endregion Change Tracking
    }
}

AIM.Web.ClientApp/AIM.Web.ClientApp/Controllers/OpenJobController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AIM.Web.Application.Client;
using AIM.Web.ClientApp.Client;
using AIM.Web.ClientApp.Models.EntityModels;

namespace AIM.Web.ClientApp.Controllers
{
    public class OpenJobController : Controller
    {
        private readonly JobServiceClient _jobClient = new JobServiceClient();
        private readonly OpenJobServiceClient _openJobClient = new OpenJobServiceClient();
        private readonly RegionServiceClient _regionClient = new RegionServiceClient();

        // GET: /OpenJob/
        public async Task<ViewResult> Index(string RegionId)
        {

            IEnumerable<OpenJob> openJobs = null;

            int regionId = Convert.ToInt32(RegionId);

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://aimadminstrativeservice.cloudapp.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // HTTP GET
                string request = "api/OpenJob?regionId=" + regionId;
                HttpResponseMessage response = await client.GetAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    openJobs = await response.Content.ReadAsAsync<IEnumerable<OpenJob>>();
                }
            }

            var region = await _regionClient.GetRegionById(regionId);
            ViewBag.RegionName = region.RegionName;

            return View(openJobs);
        }

        // GET: /OpenJob/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenJob openjob = await _openJobClient.GetOpenJobById(id);
            if (openjob == null)
            {
                return HttpNotFound();
            }

            ViewBag.Position = openjob.Job.Position;
            return View(openjob);
        }

     
    }
}

AIM.Web.ClientApp/AIM.Web.ClientApp/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AIM.Web.Application.Client;
using AIM.Web.ClientApp.Models.EntityModels;
using Newtonsoft.Json;

namespace AIM.Web.ClientApp.Controllers
{
    public class QuestionnaireController : Controller
    {
        // GET: Questionnaire
        public async Task<ViewResult> Index(int questionnaireId = 1)
        {

            IEnumerable<Question> questionnaireQuestions = null;

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://aimadminstrativeservice.cloudapp.net/");
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                // HTTP GET
                string request = "api/Question?questionnaireId=" + questionnaireId;
                HttpResponseMessage response = await client.GetAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    questionnaireQuestions = await response.Content.ReadAsAsync<IEnumerable<Question>>();
                }
            }

            // expand JSON Proterties
            if (questionnaireQuestions != null)
            {
                foreach (Question question in questionnaireQuestions)
                {
                    question.QJsonOptionList = new List<string>();
                    question.QJsonAnswerList = new List<string>();

                    var expandedQJsonProperties = JsonConvert.DeserializeObject<Question>(question.QJsonProperties);

                    question.QJsonId = expandedQJsonProperties.QJsonId;
                    question.QJsonType = expandedQJsonProperties.QJsonType;
                    question.QJsonText = expandedQJsonProperties.QJsonText;

                    for (var i = 0; i < expandedQJsonProperties.QJsonOptionList.Count(); ++i)
                    {
                        question.QJsonOptionList.Add(expandedQJsonProperties.QJsonOptionList[i]);
                    }

                    for (var i = 0; i < expandedQJsonProperties.QJsonAnswerList.Count(); ++i)
                    {
                        question.QJsonAnswerList.Add(expandedQJsonProperties.QJsonAnswerList[i]);
                    }
                }
            }
            return View(questionnaireQuestions);
        }


        public ActionResult Failed()
        {
            return View();
        }


        public ActionResult Passed()
        {
            return View();
        }

    }
}

AIM.Web.ClientApp/AIM.Web.ClientApp/Views/OpenJob/Details.cshtml
@model AIM.Web.ClientApp.Models.EntityModels.OpenJob

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>



<div>
    @using (Html.BeginForm("Index", "Home"))
    {
        <fieldset>
            <div class="jumbotron">


                <div>
                    <h4>Job Opening for @ViewBag.Position</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Region.RegionName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Region.RegionName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Store.Name)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Store.Name)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Job.Description)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Job.Description)
                        </dd>
                    </dl>
                </div>

                <div>
                    <dl class="dl-horizontal">
                        <dd>
                            <a class="btn btn-success" href="@Url.Action("Index", "Questionnaire", new { id = Model.JobId })">
                                <i class="icon-zoom-in icon-white"></i>
                                Apply Now
                            </a>
                        </dd>
                    </dl>
                </div>

                <div>
                    <p>
                        @Html.ActionLink("Back to List", "Index", new { RegionId = Model.RegionId })
                    </p>
                </div>


            </div>
            <p>
                <input type="submit" value="New Search" class="btn btn-success btn-lg btn-block icon-zoom-in icon-white" />
            </p>
        </fieldset>
    }
</div>

AIM.Web.ClientApp/AIM.Web.ClientApp/Views/OpenJob/Index.cshtml
@model IEnumerable<AIM.Web.ClientApp.Models.EntityModels.OpenJob>

@{
    ViewBag.Title = "Index";
}

<h2>
    Job Openings in @ViewBag.RegionName
</h2>

<div>
    @using (Html.BeginForm("Index", "Home"))
    {
        <fieldset>
            <div class="jumbotron">

                <table class="table">
                    <tr>
                        <th></th> <!-- Details button column -->
                        <th>
                            @Html.DisplayNameFor(model => model.Job.Position)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Store.Name)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <a class="btn btn-success" href="@Url.Action("Details", "OpenJob", new { id = item.OpenJobsId })">
                                    <i class="icon-zoom-in icon-white"></i>
                                    Details
                                </a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Job.Position)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Store.Name)
                            </td>
                        </tr>
                    }

                </table>
                @*<p>
                        @Html.ActionLink("Back to Region select", "Index", "Home")
                    </p>*@


            </div>
            <p>
                <input type="submit" value="New Search" class="btn btn-success btn-lg btn-block icon-zoom-in icon-white" />
            </p>
        </fieldset>
    }
</div>

AIM.Web.ClientApp/AIM.Web.ClientApp/Views/OpenJob/Questionnaire.cshtml
@*@model AIM.Application.Service.Entities.Models.OpenJob*@

@{
    ViewBag.Title = "Questionnaire";
    Layout = "~/Views/Shared/_Layout_Questionnaire.cshtml";
}

<h2>Questionnaire</h2>


<script>
    ("#wizard").steps();
</script>

<section id="basic">
    <h2 class="page-header">Basic Example</h2>
    <div class="wizard clearfix" id="wizard-1" role="application">
        <div class="steps clearfix"><ul role="tablist"><li class="first current" role="tab" aria-disabled="false" aria-selected="true"><a id="wizard-1-t-0" aria-controls="wizard-1-p-0" href="#wizard-1-h-0"><span class="current-info audible">current step: </span><span class="number">1.</span> Keyboard</a></li><li class="disabled" role="tab" aria-disabled="true"><a id="wizard-1-t-1" aria-controls="wizard-1-p-1" href="#wizard-1-h-1"><span class="number">2.</span> Effects</a></li><li class="disabled last" role="tab" aria-disabled="true"><a id="wizard-1-t-2" aria-controls="wizard-1-p-2" href="#wizard-1-h-2"><span class="number">3.</span> Pager</a></li></ul></div><div class="content clearfix">
            <h3 tabindex="-1" class="title current" id="wizard-1-h-0">Keyboard</h3>
            <section class="body current" id="wizard-1-p-0" role="tabpanel" aria-hidden="false" aria-labelledby="wizard-1-h-0">
                <p>Try the keyboard navigation by clicking arrow left or right!</p>
            </section>
            <h3 tabindex="-1" class="title" id="wizard-1-h-1">Effects</h3>
            <section class="body" id="wizard-1-p-1" role="tabpanel" aria-hidden="true" aria-labelledby="wizard-1-h-1" style="display: none;">
                <p>Wonderful transition effects.</p>
            </section>
            <h3 tabindex="-1" class="title" id="wizard-1-h-2">Pager</h3>
            <section class="body" id="wizard-1-p-2" role="tabpanel" aria-hidden="true" aria-labelledby="wizard-1-h-2" style="display: none;">
                <p>The next and previous buttons help you to navigate through your content.</p>
            </section>
        </div><div class="actions clearfix"><ul role="menu" aria-label="Pagination"><li class="disabled" aria-disabled="true"><a role="menuitem" href="#previous">Previous</a></li><li aria-disabled="false" aria-hidden="false"><a role="menuitem" href="#next">Next</a></li><li aria-hidden="true" style="display: none;"><a role="menuitem" href="#finish">Finish</a></li></ul></div>
    </div>
</section>

@*<div id="wizard">
    <h1>First Step</h1>
    <div>First Content</div>

    <h1>Second Step</h1>
    <div>Second Content</div>
</div>*@